### ISSUE TITLE
relation "schema_version" does not exist on fresh postgresql DB

### ISSUE THREAD

**Issue by hazcod** [temporalio/temporal#1088]
## Expected Behavior
Setup all necessary stuff in the psql database.

## Actual Behavior
Service fails wtih `relation "schema_version" does not exist.`.

## Steps to Reproduce the Problem
docker-compose:
```yaml
services:

  temporaldb:
    image: cockroachdb/cockroach:v20.1.9
    volumes:
    - data-temporal:/cockroach/cockroach-data
    tty: false
    restart: "on-failure:5"
    security_opt:
    - "no-new-privileges"
    read_only: true
    cap_drop:
    - ALL
    networks:
    - backend

  temporal:
    image: temporalio/server:1.4.1
    restart: "on-failure:5"
    environment:
    - "LOG_LEVEL=warn"
    - "AUTO_SETUP=true"
    - "DB=postgresql"
    - "DB_PORT=26257"
    - "POSTGRES_USER=root"
    - "POSTGRES_PWD=postgres"
    - "POSTGRES_SEEDS=postgres"
    - "SKIP_DEFAULT_NAMESPACE_CREATION=true"
    links:
    - temporaldb:postgres
    ports:
    - 7233
    depends_on:
    - temporaldb
```

Logs:
```
+ DB=postgresql

+ ENABLE_ES=false

+ ES_SCHEMA_SETUP_TIMEOUT_IN_SECONDS=0

+ ES_PORT=9200

+ ES_SCHEME=http

+ ES_VIS_INDEX=temporal-visibility-dev

+ RF=1

+ DEFAULT_NAMESPACE=default

+ DEFAULT_NAMESPACE_RETENTION=1

+ CASSANDRA_PORT=9042

+ export TEMPORAL_CLI_ADDRESS=172.18.0.4:7233

+ TEMPORAL_CLI_ADDRESS=172.18.0.4:7233

+ export KEYSPACE=temporal

+ KEYSPACE=temporal

+ export VISIBILITY_KEYSPACE=temporal_visibility

+ VISIBILITY_KEYSPACE=temporal_visibility

+ export DBNAME=temporal

+ DBNAME=temporal

+ export VISIBILITY_DBNAME=temporal_visibility

+ VISIBILITY_DBNAME=temporal_visibility

+ export DB_PORT=26257

+ DB_PORT=26257

+ '[' '' = autosetup ']'

+ '[' false == true ']'

+ exec bash /start-temporal.sh

+ dockerize -template /etc/temporal/config/config_template.yaml:/etc/temporal/config/docker.yaml

+ IFS=:,

+ read -ra SERVICE_LIST

++ printf -- '--service=%s ' history matching frontend worker

+ SERVICE_ARGS='--service=history --service=matching --service=frontend --service=worker '

+ exec temporal-server --root /etc/temporal --env docker start --service=history --service=matching --service=frontend --service=worker

2020/12/14 08:26:43 Loading config; env=docker,zone=,configDir=/etc/temporal/config

2020/12/14 08:26:43 Loading config files=[/etc/temporal/config/docker.yaml]

Unable to start server: sql schema version compatibility check failed: unable to read DB schema version keyspace/database: temporal error: pq: relation "schema_version" does not exist.
```
