### ISSUE TITLE
[Bug] 3 INVALID_ARGUMENT: only operation = is support for CloseTime

### ISSUE THREAD

**Issue by AmetDevops** [temporalio/temporal#1314]
**Describe the bug**

S3 integration with Temporal doesn't work properly:

```
3 INVALID_ARGUMENT: only operation = is support for CloseTime
```

**To Reproduce**

Temporal config:

```yaml
    archival:
      history:
        state: "enabled"
        enableRead: true
        provider:
          s3store:
            region: "us-east-1"
      visibility:
        state: "enabled"
        enableRead: true
        provider:
          s3store:
            region: "us-east-1"

    namespaceDefaults:
      archival:
        history:
          state: "enabled"
          URI: "s3://my-temporal-archive"
        visibility:
          state: "enabled"
          URI: "s3://my-temporal-archive"
```

**Expected behavior**
No error

**Screenshots**

<img width="1358" alt="Screenshot 2021-02-22 at 20 31 16" src="https://user-images.githubusercontent.com/39903467/108753069-f008b980-754c-11eb-8f7a-f205b8838190.png">

**Additional context**

Temporal v1.7.0
Helm installation

Found a similar bug here: https://github.com/uber/cadence/issues/3544
Duplicate in web repo: https://github.com/temporalio/web/issues/273
