### ISSUE TITLE
Struct pointer to Activities is nil when executed using ExecuteLocalActivity 

### ISSUE THREAD

**Issue by ghstahl** [temporalio/temporal#1457]
## Expected Behavior
Activities executed show not behave differently when executed using either ***ExecuteActivity*** or ***ExecuteLocalActivity***  

## Actual Behavior
***ExecuteLocalActivity***  results in the struct pointer to the activities being nil.   

## Steps to Reproduce the Problem

  [reproduced project](https://github.com/fluffy-bunny/temporal-go-localexecute-issue)   

When registering activites using a struct as such;

## Activities  
```go
type BeautifulActivities struct {
}

var MyBeautifulActivities *BeautifulActivities

func NewBeautifulActivities() *BeautifulActivities {
	return &BeautifulActivities{}
}
func (a *BeautifulActivities) ComposeGreeting(name string) (string, error) {
	if a == nil {
		// This happens when
		fmt.Println("Ermaghd me pointer is nil!")
		panic("Ermaghd me pointer is nil!")
	} else {
		fmt.Println("Nothing to see here, everything is A-OK!")
	}
	greeting := fmt.Sprintf("Hello %s!", name)
	return greeting, nil
}
```
## Registering Activities  
```go
act := app.NewBeautifulActivities()
w.RegisterActivity(act)
``` 
Results in the pointer to **\*BeautifulActivities** being nil if the activity is executed locally.  
```go 
func (a *BeautifulActivities) ComposeGreeting(name string) (string, error) {
// a is nil - panic
}
```  

```go
localOptions := workflow.LocalActivityOptions{
		StartToCloseTimeout: time.Second * 5,
}
ctx = workflow.WithLocalActivityOptions(ctx, localOptions)
err = workflow.ExecuteLocalActivity(ctx, MyBeautifulActivities.ComposeGreeting, name).Get(ctx, &result)
```

This does not happen when the activity is exeucted normally.  
```go
options := workflow.ActivityOptions{
		StartToCloseTimeout: time.Second * 5,
}
ctx = workflow.WithActivityOptions(ctx, options)
var result string
err := workflow.ExecuteActivity(ctx, MyBeautifulActivities.ComposeGreeting, name).Get(ctx, &result)
```
## Specifications

  - Version:
  - Platform:
```yaml
version: "3.5"
services:
  cassandra:
    container_name: temporal-cassandra
    image: cassandra:3.11.9
    networks:
      - temporal-network
    ports:
      - 9042:9042
  temporal:
    container_name: temporal
    depends_on:
      - cassandra
    environment:
      - CASSANDRA_SEEDS=cassandra
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
    image: temporalio/auto-setup:1.8.1
    networks:
      - temporal-network
    ports:
      - 7233:7233
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig
  temporal-admin-tools:
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:1.8.1
    networks:
      - temporal-network
    stdin_open: true
    tty: true
  temporal-web:
    container_name: temporal-web
    depends_on:
      - temporal
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
      - TEMPORAL_PERMIT_WRITE_API=true
    image: temporalio/web:1.8.1
    networks:
      - temporal-network
    ports:
      - 8088:8088
networks:
  temporal-network:
    driver: bridge
    name: temporal-network

```
