### ISSUE TITLE
Dashboard query workflow list repeatly on first page

### ISSUE THREAD

**Issue by purefun** [temporalio/temporal#1459]
## Record screen
![Record screen](https://user-images.githubusercontent.com/3140656/114668206-094f0a80-9d33-11eb-8225-a6fde072c309.gif)

## Specifications

  - Version: see docker-compose file below
  - Platform: macOS 10.15.7
  - Browsers:
      - Chrome: Version 89.0.4389.114 (Official Build) (x86_64)
      - Chrome: Version 90.0.4430.61 (Official Build) beta (x86_64)
      -  Safari: Version 13.1.3 (15609.4.1)

```yaml
# from https://github.com/temporalio/docker-compose/blob/main/docker-compose-mysql.yml
version: "3.5"
services:
  mysql:
    container_name: temporal-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    image: mysql:5.7
  temporal:
    container_name: temporal
    depends_on:
      - mysql
    environment:
      - DB=mysql
      - DB_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PWD=root
      - MYSQL_SEEDS=mysql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
    image: temporalio/auto-setup:1.8.1
    volumes:
      - ./temporal-config:/etc/temporal/config/dynamicconfig
  temporal-admin-tools:
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:1.8.1
    stdin_open: true
    tty: true
  temporal-web:
    container_name: temporal-web
    depends_on:
      - temporal
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
      - TEMPORAL_PERMIT_WRITE_API=true
    image: temporalio/web:1.8.1
    ports:
      - 8088:8088
networks:
  default:
    external:
      name: networknamehere

```
