### ISSUE TITLE
auto-setup docker container not connecting to psql over tls

### ISSUE THREAD

**Issue by michaeljguarino** [temporalio/temporal#2293]
## Expected Behavior
I've been trying to get the temporalio/auto-setup container working with zalando's postgres operator on k8s, which requires sslmode=require or greater for all connections.  As far as I can tell, there's no way to get it to configure those ssl parameters correctly.  I've set the env var SQL_TLS_ENABLED and confirmed it generates the config file in a way that looks correct, but still no dice.  Every time the entrypoint runs it emits this message:

```
temporal-sql-tool --plugin postgres --ep plural-airbyte -u airbyte -p 5432 create --db temporal
2021-12-12T18:20:56.019Z        ERROR   Unable to create SQL database.  {"error": "unable to connect to DB, tried default DB names: postgres,defaultdb, errors: [pq: pg_hba.conf rejects connection for host \"10.0.1.59\", user \"airbyte\", database \"postgres\", SSL off pq: pg_hba.conf rejects connection for host \"10.0.1.59\", user \"airbyte\", database \"defaultdb\", SSL off]", "logging-call-at": "handler.go:97"} 
```

Suggesting it reverts back to a non-tls connection

## Actual Behavior

Unable to create database or migrate tables due to lack of tls connection

## Steps to Reproduce the Problem

  1. Provision a zalando postgres db instance (or an equivalent)
  2. Run temporalio/auto-setup:1.13.1 with env vars wiring in username/secrets, etc
  3. See above error log, container crashes

## Specifications

  - Version: 1.13.1
  - Platform: docker

**Comment by michaeljguarino** [comment]
This is the persistence block of the config file, for reference:

```
persistence:
    numHistoryShards: 4
    defaultStore: default
    visibilityStore: visibility
    datastores:
        default:
            sql:
                pluginName: "postgres"
                databaseName: "temporal"
                connectAddr: "plural-airbyte:5432"
                connectProtocol: "tcp"
                user: "airbyte"
                password: "OMITTED"
                maxConns: 20
                maxIdleConns: 20
                maxConnLifetime: 1h
                tls:
                    enabled: true
                    сaFile: 
                    certFile: 
                    keyFile: 
                    enableHostVerification: false
                    serverName: 
```

**Comment by michaeljguarino** [comment]
Ok I think I found the workaround, by adding the following env vars:

```
- name: SQL_TLS
      value: 'true'
- name: SQL_TLS_DISABLE_HOST_VERIFICATION
  value: 'true'
```

Which I tracked down in the source code here: https://github.com/temporalio/temporal/blob/master/tools/sql/main.go#L110.  It was definitely not straightforwardly documented, perhaps that should be covered in the docker setup docs?

**Comment by AjayShekar01** [comment]
Thanks, this worked for me.

**Comment by gajus** [comment]
I am getting similar error:

```
Unable to start server: sql schema version compatibility check failed: pq: no pg_hba.conf entry for host "104.198.164.49", user "avnadmin", database "temporal", no encryption.
```

Adding the aforementioned ENV variables did not solve it.

**Comment by gajus** [comment]
Just tried downgrading to PostgreSQL v13.

Still getting this error:

```
{"level":"info","ts":"2022-01-31T17:23:08.336Z","msg":"Starting server for services","value":"[history matching frontend worker]","logging-call-at":"server.go:110"}
Unable to start server: sql schema version compatibility check failed: pq: no pg_hba.conf entry for host "34.136.113.111", user "avnadmin", database "temporal", SSL off.
```

**Comment by jbreiding** [comment]
@michaeljguarino reading through the comments, it appears the next steps are better documentation around the environment variables you had to dig for?

**Comment by jbreiding** [comment]
Once this PR lands, https://github.com/temporalio/docker-compose/pull/82, hopefully it will be simpler to perform this task until we refactor this process.

**Comment by mradb** [comment]
@gajus i ran into the same error with Azure Postgres v14.7 how did you fix it please ?

**Comment by weisdd** [comment]
@mradb I had to manually modify chart (only `server-job.yaml`)  to include the vars that @michaeljguarino mentioned, namely:
```yaml
            - name: SQL_TLS
              value: "true"
            - name: SQL_TLS_DISABLE_HOST_VERIFICATION
              value: "true"
```
Also, had [to whitelist `btree_gin` azure.extension](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-extensions#postgres-14-extensions):
```hcl
resource "azurerm_postgresql_flexible_server_configuration" "azure_extensions" {
  name      = "azure.extensions"
  server_id = azurerm_postgresql_flexible_server.this.id
  value     = "btree_gin"
}
```
