### ISSUE TITLE
Use Temporal with a Cassandra Astra Backend

### ISSUE THREAD

**Issue by clun** [temporalio/temporal#2419]
## Expected Behavior
As the first database to use for the persistence with temporal was Cassandra i was wondering if we could use Astra as well to avoid installing any DB locally.

## Actual Behavior
I download the zip file containing the different certificates and unzipping them in `./dynamicconfig. I got a username and password. Looking at the different samples I set up the server with a `docker-compose` in the following way:

```yaml
temporal:
    container_name: temporal
    environment:
      - DYNAMIC_CONFIG_FILE_PATH=/etc/temporal/config/dynamicconfig/development.yaml
      - DB=cassandra
      - SKIP_SCHEMA_SETUP=false
      - CASSANDRA_SEEDS=<myhost>-eu-west-1.db.astra.datastax.com
      - CASSANDRA_PORT=29042
      - CASSANDRA_USER=<my_user>
      - CASSANDRA_PASSWORD=<my_password>
      - CASSANDRA_TLS_ENABLED=true
      - CASSANDRA_CERT=/etc/temporal/config/dynamicconfig/cert
      - CASSANDRA_CERT_KEY=/etc/temporal/config/dynamicconfig/key
      - CASSANDRA_CA=/etc/temporal/config/dynamicconfig/ca.crt
      - CASSANDRA_REPLICATION_FACTOR=3
    image: temporalio/auto-setup:1.14.2
    networks:
      - temporal-network
    ports:
      - 7233:7233
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig
```

User and password are validated, port is correct but the validation does not pass:

```
+ temporal-cassandra-tool --ep <db>-db.astra.datastax.com validate-health
2022-01-25T22:19:27.930Z INFO Validating connection to cassandra cluster. {"logging-call-at": "cqlclient.go:112"}
2022/01/25 22:23:59 error: failed to connect to 63.35.186.217:29042 due to error: x509: cannot validate certificate for 63.35.186.217 because it doesn't contain any IP SANs
```

I do not see any extra file or hints I could provide to help this tool. Could you provide a sample file or spotting if I made something wrong ?

## Steps to Reproduce the Problem

  1. Create a DB in Astra and create both temporal and temporal_visibility keyspaces
  1. Download the securebundle unzip in folder dynamic config
  1. use the docker-compose file above

## Specifications

  - Version: `1.14.2`
  - Platform: Docker-compose (MAC)
