### ISSUE TITLE
Elastic over https with self-singed sertifate in auto-setup

### ISSUE THREAD

**Issue by AndreevDm** [temporalio/temporal#2502]
**Is your feature request related to a problem? Please describe.**
Hi. I am using Elasticsearch cluster witch is available only via https with self-singed сert. [Details](https://cloud.yandex.com/en-ru/docs/managed-elasticsearch/quickstart#connect).
This does not allow me to use auto-setup.sh because [curl](https://github.com/temporalio/temporal/blob/master/docker/auto-setup.sh#L245) crashes on such requests.

**Describe the solution you'd like**
To make it work, I need either to call curl with `-k` (``--insecure``) or with `--cacert  cert.crt` param.
Perhaps a more universal approach would be just to add the ES_CURL_PARAMS option.

**Describe alternatives you've considered**
The only alternative I can imagine is to write my own script. Which of course doesn't look like a good solution.

**Comment by AndreevDm** [comment]
If we agree on the name of the parameter, I can make pull request myself.

**Comment by jbreiding** [comment]
Hi @AndreevDm 

Thanks for creating the issue and explanation of the issue.

Question for you about the setup:
Can you share how are you configuring temporal server services in your environment to connect to this Elasticsearch cluster?

**Comment by jbreiding** [comment]
Digging a little bit deeper just adding this to curl options won't completely enable this scenario.

I am working through an example that will add an option to `auto-setup.sh` for this.

**Comment by AndreevDm** [comment]
We are running temporal via binary in our own containers. Сustom certificate is already installed there, so everything works fine.
Config for elactics:
```yaml  
   es-visibility:
      elasticsearch:
        version: "v7"
        url:
          scheme: "https"
          host: "${ELASTIC_ADDRESS}"
        username: admin
        password: ${ELASTIC_PASSWORD}
        indices:
          visibility: temporal_visibility_v1_dev
```

We wan't to use auto-setup docker image for initial db configuration and schema update. 

But you are absolutely right that in general, when using temporal-provided docker images, problems will arise.
