### ISSUE TITLE
Document POSTGRES_SEEDS (or better yet, use a descriptive var name)

### ISSUE THREAD

**Issue by colelawrence** [temporalio/temporal#2668]
**Is your feature request related to a problem? Please describe.**
I have been very frustrated over the last two hours, because I haven't seen any documentation for how to actually customize the connection for my postgresql database.

I have finally realized after searching this codebase for `POSTGRES_SEEDS` that it is actually being used as "postgres connection host".

**Describe the solution you'd like**

I would strongly recommend rethinking the consistency of these environment variables, as it has lead me and to a great deal of confusion, or documenting all the docker-compose files with descriptions.

**Comment by jbreiding** [comment]
Thanks, we are going to track this under a larger project to reconcile all the different ways temporal can be configured to a simple, and documented path.

**Comment by gajus** [comment]
Unbelievable. @colelawrence This prob saved me hours of search 🤦

**Comment by fowlmouth** [comment]
In 2023 the best source for info about POSTGRES_SEEDS is still searching through the issues in github

**Comment by happyxhw** [comment]
In 2023 the best source for info about POSTGRES_SEEDS is still searching through the issues in github

**Comment by MysticalMount** [comment]
Ditto this, just realised myself but its not obvious at all

**Comment by jxc876** [comment]
I ran into the same thing,

I was super confused by `POSTGRES_SEEDS` I assumed it was some type of Seed for randomness.

But then had to dig and found this:

```
        default:
            sql:
                pluginName: "{{ $db }}"
                databaseName: "{{ default .Env.DBNAME "temporal" }}"
                connectAddr: "{{ default .Env.POSTGRES_SEEDS "" }}:{{ default .Env.DB_PORT "5432" }}"
```

* https://github.com/temporalio/temporal/blob/main/docker/config_template.yaml#L102
