### ISSUE TITLE
Feature: add option to auto-create domain

### ISSUE THREAD

**Issue by hazcod** [temporalio/temporal#286]
In a microservices setup, one cannot easily perform manual actions and re-deploys happen regularely. It would be nice to have the client auto-create domains if they do not exist, possibly under a configuration flag.

So we don't have to do things that sometimes fail like:
```yaml
  cadence:
    image: ubercadence/server:master-auto-setup
    networks:
    - backend
    environment:
    - "CASSANDRA_SEEDS=cassandra"
    - "STATSD_ENDPOINT=statsd:8125"
    - "DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml"
    links:
    - statsd
    - cassandra
    ports:
    - 7933
    depends_on:
    - cassandra
    - statsd

  cadence-init:
    image: ubercadence/server:master-auto-setup
    networks:
    - backend
    links:
    - cadence
    depends_on:
    - cadence
    command: ["cadence", "--address=cadence:7933", "--domain=my-domain", "domain", "register"]
    environment:
    - CADENCE_CLI_SHOW_STACKS=1
```
