### ISSUE TITLE
Feature: add example with cockroachdb

### ISSUE THREAD

**Issue by hazcod** [temporalio/temporal#287]
I'm really interested in running this alongside cockroachdb, which is a postgres-compliant cloud native database with easy HA/clustering.
On the plus side, it's written in Go so I run it statically compiled in a scratch container.
https://github.com/ironpeakservices/iron-cockroachdb

I would love to see a docker-compose.yml example using cockroach and/or postgres.

**Comment by hazcod** [comment]
CC https://github.com/cockroachdb/cockroach/issues/47599

**Comment by hazcod** [comment]
Compose:
```yaml
  cadence-db:
    hostname: cadence-db
    image: docker.pkg.github.com/ironpeakservices/iron-cockroachdb/iron-cockroachdb:19.1.5
    container_name: cadence-db
    tty: false
    restart: "on-failure:5"
    security_opt:
    - "no-new-privileges"
    read_only: true
    cap_drop:
    - ALL
    networks:
    - backend
    command: ["start", "--insecure"]

  statsd:
    image: graphiteapp/graphite-statsd
    networks:
    - backend

  cadence:
    image: ubercadence/server:master-auto-setup
    networks:
    - backend
    environment:
    - "DB=postgres"
    - "DB_PORT=26257"
    - "POSTGRES_USER=root"
    - "POSTGRES_PWD="
    - "POSTGRES_SEEDS=postgres"
    - "STATSD_ENDPOINT=statsd:8125"
    - "DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml"
    links:
    - statsd
    - cadence-db:postgres
    ports:
    - 7933
    depends_on:
    - cadence-db
    - statsd

  cadence-init:
    image: ubercadence/server:master-auto-setup
    networks:
    - backend
    links:
    - cadence
    depends_on:
    - cadence
    command: ["cadence", "--address=cadence:7933", "--domain=micro-domain", "domain", "register"]
```
