### ISSUE TITLE
Surprising clusterMetadata override

### ISSUE THREAD

**Issue by wxing1292** [temporalio/temporal#3104]
## Expected Behavior
If DB is not initialized, static config of cluster metadata should be 
* either respected & persisted into DB
* or deprecated completely

## Actual Behavior
```
clusterMetadata:
  enableGlobalNamespace: true
  failoverVersionIncrement: 10
  masterClusterName: "cluster-a"
  currentClusterName: "cluster-a"
  clusterInformation:
    cluster-a:
      enabled: true
      initialFailoverVersion: 3
      rpcName: "frontend"
      rpcAddress: "localhost:7233"
    cluster-b:
      enabled: true
      initialFailoverVersion: 2
      rpcName: "frontend"
      rpcAddress: "localhost:8233"
```      
Using above static config & clean DB & after 1s ish, the `cluster-b` section will be deleted 

## Steps to Reproduce the Problem
See above

## Specifications

  - Version: 1.16.x+
  - Platform: Mac & Intel
