### ISSUE TITLE
Build docker images with integer UID/GID and use the same one on all images

### ISSUE THREAD

**Issue by skandragon** [temporalio/temporal#3453]
## Expected Behavior

Be able to deploy in kubernetes in a restricted environment without a lot of work.

## Actual Behavior

It's a bit of work.

## Steps to Reproduce the Problem

In a restricted world, I need to define some characteristics of the container.  Kubernetes can query the image and detect if it runs as non-root, for instance, but not if the UID is a username and not a UID.

My current workaround is more verbose than needed:

```
securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: RuntimeDefault
  runAsUser: 1000
  runAsGroup: 1000
```

If the UIDs were not 0, I could leave off at least the last two items.

Also, the web container uses 5000 for the temporal user...  which is likely an unneeded difference.

## Specifications

  - Version:  1.18.0
  - Platform: Any (kubernetes)
