### ISSUE TITLE
OTEL env var not taken into account

### ISSUE THREAD

**Issue by mlcdf** [temporalio/temporal#4041]
## Expected Behavior

Hello :)

Sending trace to a jaeger instance by specifying [`OTEL*` env variables](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md) as it's said in [the docs](https://github.com/temporalio/temporal/blob/7b6ce254525b4ed7776e8ba6bf701da493eea1de/develop/docs/tracing.md).

```
$ docker inspect temporal-server | grep OTEL
                "OTEL_EXPORTER_OTLP_INSECURE=true",
                "OTEL_LOG_LEVEL=debug",
                "OTEL_TRACES_EXPORTER=otlp",
                "OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=grpc",
                "OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=jaeger:4317",
                "OTEL_EXPORTER_OTLP_TRACES_INSECURE=true",
```

## Actual Behavior

`OTEL_*` env variables aren't taken into account. 

The only way I managed to make this work is to use this config: 

```
otel:
  exporters:
    - kind:
        signal: traces
        model: otlp
        protocol: grpc
      spec:
        connection:
          insecure: true
          endpoint: jaeger:4317
```

## Steps to Reproduce the Problem

1. Start jaeger using https://github.com/temporalio/temporal/blob/master/develop/docker-compose/docker-compose.jaeger.yml
2. Start a temporal-server with the following env variable
```
            OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "jaeger:4317"
            OTEL_EXPORTER_OTLP_TRACES_PROTOCOL: grpc
            OTEL_EXPORTER_OTLP_TRACES_INSECURE: "true"
            OTEL_EXPORTER_OTLP_INSECURE: "true"
            OTEL_EXPORTER_OTLP_SPAN_INSECURE: "true"
```
3. Open the jaeger UI: there is now trace

## Specifications

  - Version: Temporal 1.18.1
  - Platform: Docker (running on Debian 10)
