### ISSUE TITLE
Repeated "New timer generated is less than read level" in logs after adding node to cluster

### ISSUE THREAD

**Issue by kelnos** [temporalio/temporal#425]
## Expected Behavior

After adding a second node to a newly-bootstrapped one-node temporal cluster, logs should be generally quiet.

## Actual Behavior

Instead, after adding the second node, I see "New timer generated is less than read level" repeated once per second in the logs of the original node (logs of second node are quiet).  Full example log line:
```
{"level":"warn","ts":"2020-06-01T18:08:52.273-0700","msg":"New timer generated is less than read level","service":"history","shard-id":111,"address":"[redacted]:7234","wf-namespace-id":"892c1d1f-e202-49dc-bc77-97268a84c9ef","wf-id":"eae6d2bc-89fe-4ac5-a544-a8087e3deede","timestamp":"2020-06-01T17:14:41.689-0700","cursor-timestamp":"2020-06-01T18:08:53.265-0700","shard-update":"ShardAllocateTimerBeforeRead","logging-call-at":"shardContext.go:1130"}
```
Note that the IP address in the `address` field refers to the same node that is generating the log.

## Steps to Reproduce the Problem

  1. Set up a fresh Cassandra keyspace and ES index.
  1. Boot a single Temporal node and create a test namespace.
  1. Start a workflow/activity worker and start a workflow execution to test that it works.
  1. Boot a second Temporal node and wait for it to finish joining the cluster.
  1. Repeated log message should start.

I am not certain that step 3 is required, but this is what I did, so I'm detailing it here.

## Specifications

  - Version: 0.23.1
  - Platform: Amazon Linux 2018.03 + Docker 18.09.9

## More Information

After running `tctl admin cluster describe` against both Temporal nodes, I can see that they both have the same view of the cluster, and that they both see all four services on both nodes.

**Comment by samarabbas** [comment]
@kelnos this log usually is emitted when a certain protection kicks in which guarantees we don't generate timers less than read level resulting us skipping certain timers.  This does not indicate a problem with the system, but having this log being emitted so frequently is definitely we will look it.

**Comment by kelnos** [comment]
Thanks!  Just to follow up, it's been ~4 hours and it's still logging that, still once per second.  So it does appear that something is "stuck".

**Comment by kelnos** [comment]
Samar & I had a zoom call, and the feedback is that I was setting a workflow execution timeout for a cron schedule workflow, which I shouldn't be doing.  What I was doing was this:
```java
final DemoCronWorkflow demoCronWorkflow = workflowClient.newWorkflowStub(
        DemoCronWorkflow.class,
        WorkflowOptions.newBuilder()
                .setWorkflowIdReusePolicy(WorkflowIdReusePolicy.AllowDuplicate)
                .setWorkflowExecutionTimeout(Duration.ofSeconds(10))
                .setWorkflowTaskTimeout(Duration.ofSeconds(20))
                .setTaskList(DemoCronWorkflow.TASK_LIST_NAME)
                .setWorkflowId(WORKFLOW_ID)
                .build()
);
WorkflowClient.start(demoCronWorkflow::logEveryMinute);
```
The workflow itself is just a simple one-liner that writes to the log when it runs, which it's scheduled to do every minute (`@CronSchedule("* * * * *")`).

Sample history for a single run (copy/paste destroyed formatting, so here's a screenshot):
![history](https://user-images.githubusercontent.com/544991/84082694-24bfeb00-a995-11ea-8177-1f1316a7e0aa.png)

I'm going to remove the execution timeout, cancel execution of the current workflow, and start it anew to see if that fixes things, and will report back.

**Comment by kelnos** [comment]
Good news: not setting the workflow execution timeout worked.  The repeated log message in the temporal log is gone, and the cron workflow is working correctly and running once per minute.

**Comment by kelnos** [comment]
We've been running into this again (with Temporal 1.0.0), and it's with a regularly-started workflow, not a cron workflow.  The service in question is just doing:
```java
final Workflow workflow = workflowClient.newWorkflowStub(
            Workflow.class,
            WorkflowOptions.newBuilder()
                .setWorkflowId(event.getId())
                .setWorkflowIdReusePolicy(WorkflowIdReusePolicy.WORKFLOW_ID_REUSE_POLICY_REJECT_DUPLICATE)
                .setWorkflowExecutionTimeout(Duration.ofMinutes(10))
                .setWorkflowTaskTimeout(Duration.ofMinutes(1))
                .setRetryOptions(RetryOptions.newBuilder()
                    .setInitialInterval(Duration.ofSeconds(1))
                    .setBackoffCoefficient(2)
                    .setMaximumInterval(Duration.ofSeconds(20))
                    .setMaximumAttempts(3)
                    .build()
                )
                .setTaskQueue(RecyclingEventWorkflow.TASK_QUEUE_NAME)
                .build()
        );
        WorkflowClient.start(workflow::processEvent, event);
```

We're also seeing an issue where (sometimes, but not always, after a flood of these log messages), the temporal-server process pegs a CPU at 100% and stops responding to requests.  Not sure if that's related to this, but either way it's very concerning.

**Comment by kelnos** [comment]
Some more info: the workflow runs appear to complete successfully, but I see this warning in the log quite often (upwards of 15 times per minute).  At most there seem to be one or two workflow runs per minute, but usually only one, and the run takes only a few seconds at most.  Also just noticed that I see it with other workflows, not just the one above.

**Comment by kelnos** [comment]
Just updated to the new 1.1.0 release and I'm still seeing the warning.

**Comment by samarabbas** [comment]
@kelnos this log does not represent an issue with the system.  This usually happens if a timer is created with a very short interval and while the transaction is outstanding readlevel for timer queue moves beyond the visibility time for the new timer.  
@wxing1292 can you convert this to a metric instead as this log is continuously causing confusion to users?  At the minimum we should change the log level to info instead of warning.

@kelnos your 100% cpu is more concerning.  Can you provide more information about the setup?
1) Cluster size?
2) Are you deploying each role as separate instances?
3) Which role goes into 100% cpu
4) what kind of workload you are running through the cluster.

**Comment by wxing1292** [comment]
@kelnos can you plz take a CPU & mem profile?

CPU:
```zsh
go tool pprof -pdf http://localhost:7936/debug/pprof/profile\?seconds\=30
```

Mem:
```zsh
go tool pprof -pdf http://localhost:7936/debug/pprof/heap
```

**Comment by kelnos** [comment]
@samarabbas thanks for the clarification!

>     1. Cluster size?

Two nodes

>     2. Are you deploying each role as separate instances?

No, all roles on the same instance.

>     3. Which role goes into 100% cpu

Unknown.

>     4. what kind of workload you are running through the cluster.

Very light workload, currently single-digit concurrent workflow invocations.  All invocations are relatively short lived and either complete within a few seconds or few tens of seconds.

@wxing1292 I assume the CPU/mem profiles will only be useful to capture while the system is in the bad state?  It seems to be happening once per day or two, so I should be able to get that for you soon.

**Comment by wxing1292** [comment]
> No, all roles on the same instance.

I would really recommend putting different services (frontend / matching / history) on different nodes / hosts if you are running production traffic.

**Comment by kelnos** [comment]
Unfortunately when the server gets into this state, the pprof endpoint does not respond.  I get something similar to:
```
Fetching profile over HTTP from http://localhost:7936/debug/pprof/heap
http://localhost:7936/debug/pprof/heap: Get http://localhost:7936/debug/pprof/heap: net/http: timeout awaiting response headers
failed to fetch any source profiles
```
Verified that pprof is indeed working when the server is working normally.

I did manage to get a goroutine dump by sending a `SIGQUIT`: [lockup.log](https://github.com/temporalio/temporal/files/5400336/lockup.log)

**Comment by kelnos** [comment]
Any thoughts on how to proceed here?  This is a huge blocker for us, as I'm seeing node failures in our development environment nearly daily (with all 1.0.0+ releases).  We're still running 0.30.0 in prod with no failures.

**Comment by wxing1292** [comment]
@kelnos 
what DB are you using?
any configuration that you can share?

one important thing, can you plz try deploy the service as one service per host, rather than all in one?

**Comment by wxing1292** [comment]
btw i will be on slack: https://temporalio.slack.com/join/shared_invite/zt-c1e99p8g-beF7~ZZW2HP6gGStXD8Nuw#/

**Comment by kelnos** [comment]
@wxing1292 I'm using Cassandra, and our configuration is using `docker/config_template.yaml` with some minor changes.  Rendered, it looks like this on one of my nodes:
```yaml
log:
    stdout: true
    level: info

persistence:
    numHistoryShards: 512
    defaultStore: default
    visibilityStore: visibility
    advancedVisibilityStore: es-visibility
    datastores:
        default:
            cassandra:
                hosts: 127.0.0.1:10002
                keyspace: temporal
        visibility:
            cassandra:
                hosts: 127.0.0.1:10002
                keyspace: temporal_visibility
        es-visibility:
            elasticsearch:
                url:
                    scheme: "http"
                    host: "localhost:8422"
                indices:
                    visibility: temporal-visibility

global:
    membership:
        maxJoinDuration: 240s
        broadcastAddress: 
    tls:
        internode:
            server:
                certFile: 
                keyFile: 
                requireClientAuth: false
                clientCaFiles:
                    - 
            client:
                rootCaFiles:
                    - 
        frontend:
            server:
                certFile: 
                keyFile: 
                requireClientAuth: false
                clientCaFiles:
                    - 
                    - 
            client:
                rootCaFiles:
                    - 

services:
    frontend:
        rpc:
            grpcPort: 7233
            membershipPort: 6933
            bindOnIP: 172.22.199.254
        metrics:
            statsd:
                hostPort: localhost:8127
                prefix: ops.temporal.frontend

    matching:
        rpc:
            grpcPort: 7235
            membershipPort: 6935
            bindOnIP: 172.22.199.254
        metrics:
            statsd:
                hostPort: localhost:8127
                prefix: ops.temporal.matching

    history:
        rpc:
            grpcPort: 7234
            membershipPort: 6934
            bindOnIP: 172.22.199.254
        metrics:
            statsd:
                hostPort: localhost:8127
                prefix: ops.temporal.history

    worker:
        rpc:
            grpcPort: 7239
            membershipPort: 6939
            bindOnIP: 172.22.199.254
        metrics:
            statsd:
                hostPort: localhost:8127
                prefix: ops.temporal.worker

clusterMetadata:
    enableGlobalNamespace: false
    failoverVersionIncrement: 10
    masterClusterName: "active"
    currentClusterName: "active"
    clusterInformation:
        active:
            enabled: true
            initialFailoverVersion: 1
            rpcName: "frontend"
            rpcAddress: "127.0.0.1:7233"

dcRedirectionPolicy:
    policy: "noop"
    toDC: ""

archival:
  history:
    state: "enabled"
    enableRead: true
    provider:
      filestore:
        fileMode: "0666"
        dirMode: "0766"
  visibility:
    state: "enabled"
    enableRead: true
    provider:
      filestore:
        fileMode: "0666"
        dirMode: "0766"

namespaceDefaults:
  archival:
    history:
      state: "disabled"
      URI: "file:///tmp/temporal_archival/development"
    visibility:
      state: "disabled"
      URI: "file:///tmp/temporal_vis_archival/development"

kafka:
    tls:
        enabled: false
    clusters:
        test:
            brokers:
                - 127.0.0.1:10003
    topics:
        Architecture.TemporalVisibility:
            cluster: test
        Architecture.TemporalVisibilityDlq:
            cluster: test
    applications:
        visibility:
            topic: Architecture.TemporalVisibility
            dlq-topic: Architecture.TemporalVisibilityDlq

publicClient:
    hostPort: 172.22.199.254:7233

dynamicConfigClient:
    filepath: /etc/temporal/config/dynamicconfig/twilio.yaml
    pollInterval: "60s"
```
The dynamic config looks like:
```yaml
history.EnableConsistentQueryByNamespace:
  - value: true
```

Just a note that Cassandra and ES are not running on the local node; the "localhost" there is just the entry point into our service mesh.

I can try doing one service per node, but that might take me a little bit of time to set up.

I'm also on your slack, as `@btarricone`.  If you think it'll be easier to continue discussion there, I'm happy to chat there instead.
