### ISSUE TITLE
Feature: implement docker healthcheck

### ISSUE THREAD

**Issue by hazcod** [temporalio/temporal#453]
**Is your feature request related to a problem? Please describe.**
Currently docker will assume the container is ready once it is running, while the temporal engine is still warming up, leading to all sorts of problems.

**Describe the solution you'd like**
Implement the HEALTHCHECK directive in your Dockerfile(s).

**Describe alternatives you've considered**
Restarting clients.

**Additional context**

**Comment by berardino** [comment]
As a work around, until the HEALTHCHECK is added to the docker image,  I was able to implement a healthcheck in the docker-compose file as follow:

```yaml
healthcheck:
      test: [ "CMD", "tctl","cluster","h" ]
      interval: 10s
      timeout: 1m
      retries: 10
```

**Comment by tarampampam** [comment]
In addition, if you didn't want to set the container name, you can force temporal listening on any interface:

```yaml
services:
  temporal:
    image: temporalio/auto-setup:1.19
    ports: ['7233:7233/tcp']
    environment: # https://github.com/temporalio/docker-builds/blob/main/docker/auto-setup.sh
      # ...
      BIND_ON_IP: 0.0.0.0
      TEMPORAL_BROADCAST_ADDRESS: 127.0.0.1
    healthcheck:
      test: ['CMD-SHELL', 'tctl --address 127.0.0.1:7233 workflow list']
      interval: 1s
      timeout: 5s
      start_period: 2s
```

**Comment by Mahmoud-Elbahnasawy** [comment]
This is the health check that worker for me 
```
      test:
        ["CMD","tctl", "--address", "temporal:7233", "workflow", "list", "||", "exit 1"]
      interval: 1s
      timeout: 5s
      retries: 30
```
      and i added a condition on the container that needs to the wait the for the health check command to be succeeded this condition 

```
    depends_on:
      temporal:
        condition: service_healthy
```
