### ISSUE TITLE
Temporal can't connect to Elasticsearch with enabled TLS

### ISSUE THREAD

**Issue by ganievs** [temporalio/temporal#4695]
## Expected Behavior
Temporal cluster establishes connection with  Elasticsearch.

## Actual Behavior
"no ElasticSearch node available"

## Steps to Reproduce the Problem
  1. Setup elastic 8 version with enabled TLS on the HTTP layer
  2. Set `scheme: "https"` in Temporal server config
```yaml
        elasticsearch:
          version: "v8"
          url:
            scheme: "https"
```

## Specifications

  - Temporal Version: 1.21.3
  - Elasticsearch Version: 8.6.2
  - Platform: Kubernetes

**Comment by ganievs** [comment]
Hi all! Seems like the [client library] (https://github.com/temporalio/temporal/blob/fbd0de731af608acee2840673769042f15ec8404/go.mod#L26C5-L26C5)  that you're using, doesn't have actual support for 8 version of Elasticsearch and not maintained anymore https://github.com/olivere/elastic/issues/1533. 
Do you have any plans to move to the official go [lib](https://github.com/elastic/go-elasticsearch)

**Comment by rodrigozhou** [comment]
Did you set up the certs correctly? Are they from a known issuer?
Please provide more details of how you set up.

**Comment by ganievs** [comment]
I do requests to the Elasticsearch API from my host with the same credentials and everything works.
Also, I use https://github.com/prometheus-community/elasticsearch_exporter which connects to the Elasticsearch instance and it also works well. Based on this, I can say that the certificates are configured correctly.
> Are they from a known issuer?
Yes, I used Let's Encrypt for certificate request

**Comment by rodrigozhou** [comment]
Can you share your config? Does it look like this?
```
      elasticsearch:
        version: "v8"
        url:
          scheme: "https"
          host: "127.0.0.1:9200"
        username: <username>
        password: <password>
```
