### ISSUE TITLE
Unable to start 1.21.4 cluster with archival disabled

### ISSUE THREAD

**Issue by vanhtuan0409** [temporalio/temporal#4715]
## Expected Behavior

Able to upgrade temporal cluster from 1.20.4 to 1.21.4 with archival disabled

## Actual Behavior

Server crash after upgrading to 1.21.4

## Steps to Reproduce the Problem

  1. Start cluster 1.20 with the bellow config
  2. Let's the cluster run for a while
  3. Upgrade cluster to 1.21.4

```
archival:
  history:
    state: "disabled"
  visibility:
    state: "disabled"
```

## Specifications

  - Version: 1.21.4
  - Platform: Linux
 
Suspect related issue: https://github.com/temporalio/temporal/issues/4638
