### ISSUE TITLE
Unable to update Elasticsearch mapping: elastic: Error 403 on Create Custom Attributes

### ISSUE THREAD

**Issue by DodgeCamaro** [temporalio/temporal#4773]
## Expected Behavior
Created Custom Attribute

## Actual Behavior

`Error: unable to add search attributes: System Workflow with WorkflowId temporal-sys-add-search-attributes-workflow and RunId 10fdc88f-8ef7-4936-b06d-f309a836125d returned an error: workflow execution error (type: temporal-sys-add-search-attributes-workflow, workflowID: temporal-sys-add-search-attributes-workflow, runID: 10fdc88f-8ef7-4936-b06d-f309a836125d): unable to execute activity: AddESMappingFieldActivity: activity error (type: AddESMappingFieldActivity, scheduledEventID: 5, startedEventID: 6, identity: 1@temporal-worker-7cfc5bf56d-ll9lj@): unable to update Elasticsearch mapping: elastic: Error 403 (Forbidden): no permissions for [] and User [name=temporal, backend_roles=[], requestedTenant=null] [type=security_exception] (type: wrapError, retryable: true): unable to execute activity`

## Steps to Reproduce the Problem
Same error with two command below
  1. `temporal operator search-attribute create --name CustomTest --type Keyword`
  2.  `tctl admin cl asa --name CustomTest --type Keyword`
## Specifications

  - Version: 1.20.4
  - Platform: Temporal Self-Hosted
  Advanced Visibility AWS Opensearch 2.5 + AWS RDS Postgres 13.8

**Comment by rodrigozhou** [comment]
@DodgeCamaro Can you check if the Elasticsearch user `temporal` has the right permissions to update the mapping? Please take a look at this [page](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html#put-mapping-api-prereqs:~:text=If%20the%20Elasticsearch%20security%20features%20are%20enabled%2C%20you%20must%20have%20the%20manage%20index%20privilege%20for%20the%20target%20data%20stream%2C%20index%2C%20or%20alias.).

**Comment by DodgeCamaro** [comment]
@rodrigozhou Hi.
I've use OpenSearch master user with full access to cluster

**Comment by rodrigozhou** [comment]
Can you share your visibility config?

**Comment by DodgeCamaro** [comment]
@rodrigozhou Hello, sure!
```
global:
    membership:
        maxJoinDuration: 30s
        broadcastAddress: '10.0.3.79'
    pprof:
        port: 0
    tls:
        internode:
            client:
                serverName: ""
                disableHostVerification: false
                rootCaFiles: []
                rootCaData: []
                forceTLS: false
            server:
                certFile: ""
                keyFile: ""
                clientCaFiles: []
                certData: ""
                keyData: ""
                clientCaData: []
                requireClientAuth: false
            hostOverrides: {}
        frontend:
            client:
                serverName: ""
                disableHostVerification: false
                rootCaFiles: []
                rootCaData: []
                forceTLS: false
            server:
                certFile: ""
                keyFile: ""
                clientCaFiles: []
                certData: ""
                keyData: ""
                clientCaData: []
                requireClientAuth: false
            hostOverrides: {}
        systemWorker:
            certFile: ""
            keyFile: ""
            certData: ""
            keyData: ""
            client:
                serverName: ""
                disableHostVerification: false
                rootCaFiles: []
                rootCaData: []
                forceTLS: false
        remoteClusters: {}
        expirationChecks:
            warningWindow: 0s
            errorWindow: 0s
            checkInterval: 0s
        refreshInterval: 0s
    metrics:
        tags:
            type: 'frontend'
        excludeTags: {}
        prefix: ""
        perUnitHistogramBoundaries: {}
        m3: null
        statsd: null
        prometheus:
            framework: ""
            listenAddress: 0.0.0.0:9090
            handlerPath: ""
            listenNetwork: ""
            timerType: histogram
            defaultHistogramBoundaries: []
            defaultHistogramBuckets: []
            defaultSummaryObjectives: []
            onError: ""
            sanitizeOptions: null
    authorization:
        jwtKeyProvider:
            keySourceURIs: []
            refreshInterval: 0s
        permissionsClaimName: ""
        authorizer: ""
        claimMapper: ""
persistence:
    defaultStore: default
    visibilityStore: visibility
    secondaryVisibilityStore: ""
    advancedVisibilityStore: advancedVisibility
    numHistoryShards: 4
    datastores:
        advancedVisibility:
            faultInjection: null
            cassandra: null
            sql: null
            customDatastore: null
            elasticsearch:
                version: v7
                url:
                    scheme: https
                    opaque: ""
                    user: null
                    host: opensearch
                    path: ""
                    rawpath: ""
                    omithost: false
                    forcequery: false
                    rawquery: ""
                    fragment: ""
                    rawfragment: ""
                username: temporal
                password: 'password'
                indices:
                    visibility: temporal_visibility
                logLevel: ""
                aws-request-signing:
                    enabled: false
                    region: ""
                    credentialProvider: ""
                    static:
                        accessKeyID: ""
                        secretAccessKey: ""
                        token: ""
                closeIdleConnectionsInterval: 0s
                enableSniff: false
                enableHealthcheck: false
        default:
            faultInjection: null
            cassandra: null
            sql:
                user: temporal
                password: 'password'
                pluginName: postgres
                databaseName: temporal
                connectAddr: temporal:5432
                connectProtocol: tcp
                connectAttributes: {}
                maxConns: 0
                maxIdleConns: 0
                maxConnLifetime: 0s
                taskScanPartitions: 0
                tls: null
            customDatastore: null
            elasticsearch: null
        visibility:
            faultInjection: null
            cassandra: null
            sql:
                user: temporal
                password: 'password'
                pluginName: postgres
                databaseName: temporal_visibility
                connectAddr: temporal:5432
                connectProtocol: tcp
                connectAttributes: {}
                maxConns: 0
                maxIdleConns: 0
                maxConnLifetime: 0s
                taskScanPartitions: 0
                tls: null
            customDatastore: null
            elasticsearch: null
log:
    stdout: true
    level: info
    outputFile: ""
    format: ""
    development: false
clusterMetadata:
    enableGlobalNamespace: false
    failoverVersionIncrement: 10
    masterClusterName: temporal
    currentClusterName: temporal
    clusterInformation:
        temporal:
            enabled: true
            initialFailoverVersion: 1
            rpcAddress: 127.0.0.1:7233
dcRedirectionPolicy:
    policy: ""
services:
    frontend:
        rpc:
            grpcPort: 7233
            membershipPort: 6933
            bindOnLocalHost: false
            bindOnIP: 0.0.0.0
    history:
        rpc:
            grpcPort: 7234
            membershipPort: 6934
            bindOnLocalHost: false
            bindOnIP: 0.0.0.0
    matching:
        rpc:
            grpcPort: 7235
            membershipPort: 6935
            bindOnLocalHost: false
            bindOnIP: 0.0.0.0
    worker:
        rpc:
            grpcPort: 7239
            membershipPort: 6939
            bindOnLocalHost: false
            bindOnIP: 0.0.0.0
archival:
    history:
        state: enabled
        enableRead: true
        provider:
            filestore: null
            gstorage: null
            s3store:
                region: us-east-2
                endpoint: null
                s3ForcePathStyle: false
    visibility:
        state: enabled
        enableRead: true
        provider:
            filestore: null
            s3store:
                region: us-east-2
                endpoint: null
                s3ForcePathStyle: false
            gstorage: null
publicClient:
    hostPort: ""
    forceTLSConfig: ""
dynamicConfigClient:
    filepath: /etc/temporal/config/dynamic_config.yaml
    pollInterval: 10s
namespaceDefaults:
    archival:
        history:
            state: enabled
            URI: s3://<bucket_name>
        visibility:
            state: enabled
            URI: s3://<bucket_name>
otel: {}
```

**Comment by rodrigozhou** [comment]
@DodgeCamaro I can see you're using dual visibility setting, ie., setting up two visibiility storages. One using Postgres and another using Elasticsearch. Is that on purpose?

Adding search attributes while in dual visibility mode is not supported (WIP).

**Comment by DodgeCamaro** [comment]
@rodrigozhou 
This doesn't work with AWS RDS + AWS OpenSearch
docker.yaml below with postgres and opensearch setup at cluster.

```
global:
    membership:
        maxJoinDuration: 30s
        broadcastAddress: '10.0.2.30'
    pprof:
        port: 0
    tls:
        internode:
            client:
                serverName: ""
                disableHostVerification: false
                rootCaFiles: []
                rootCaData: []
                forceTLS: false
            server:
                certFile: ""
                keyFile: ""
                clientCaFiles: []
                certData: ""
                keyData: ""
                clientCaData: []
                requireClientAuth: false
            hostOverrides: {}
        frontend:
            client:
                serverName: ""
                disableHostVerification: false
                rootCaFiles: []
                rootCaData: []
                forceTLS: false
            server:
                certFile: ""
                keyFile: ""
                clientCaFiles: []
                certData: ""
                keyData: ""
                clientCaData: []
                requireClientAuth: false
            hostOverrides: {}
        systemWorker:
            certFile: ""
            keyFile: ""
            certData: ""
            keyData: ""
            client:
                serverName: ""
                disableHostVerification: false
                rootCaFiles: []
                rootCaData: []
                forceTLS: false
        remoteClusters: {}
        expirationChecks:
            warningWindow: 0s
            errorWindow: 0s
            checkInterval: 0s
        refreshInterval: 0s
    metrics: null
    authorization:
        jwtKeyProvider:
            keySourceURIs: []
            refreshInterval: 0s
        permissionsClaimName: ""
        authorizer: ""
        claimMapper: ""
persistence:
    defaultStore: default
    visibilityStore: visibility
    secondaryVisibilityStore: ""
    advancedVisibilityStore: advancedVisibility
    numHistoryShards: 3
    datastores:
        advancedVisibility:
            faultInjection: null
            cassandra: null
            sql: null
            customDatastore: null
            elasticsearch:
                version: v7
                url:
                    scheme: http
                    opaque: ""
                    user: null
                    host: opensearch:9200
                    path: ""
                    rawpath: ""
                    omithost: false
                    forcequery: false
                    rawquery: ""
                    fragment: ""
                    rawfragment: ""
                username: temporal
                password: '&C8P0Hl9V5d'
                indices:
                    visibility: temporal_visibility
                logLevel: ""
                aws-request-signing:
                    enabled: false
                    region: ""
                    credentialProvider: ""
                    static:
                        accessKeyID: ""
                        secretAccessKey: ""
                        token: ""
                closeIdleConnectionsInterval: 0s
                enableSniff: false
                enableHealthcheck: false
        default:
            faultInjection: null
            cassandra: null
            sql:
                user: temporal
                password: 'pass'
                pluginName: postgres
                databaseName: temporal
                connectAddr: postgres:5432
                connectProtocol: tcp
                connectAttributes: {}
                maxConns: 0
                maxIdleConns: 0
                maxConnLifetime: 0s
                taskScanPartitions: 0
                tls: null
            customDatastore: null
            elasticsearch: null
        visibility:
            faultInjection: null
            cassandra: null
            sql:
                user: temporal
                password: 'pass'
                pluginName: postgres
                databaseName: temporal_visibility
                connectAddr: postgres:5432
                connectProtocol: tcp
                connectAttributes: {}
                maxConns: 0
                maxIdleConns: 0
                maxConnLifetime: 0s
                taskScanPartitions: 0
                tls: null
            customDatastore: null
            elasticsearch: null
log:
    stdout: true
    level: info
    outputFile: ""
    format: ""
    development: false
clusterMetadata:
    enableGlobalNamespace: false
    failoverVersionIncrement: 10
    masterClusterName: temporal
    currentClusterName: temporal
    clusterInformation:
        temporal:
            enabled: true
            initialFailoverVersion: 1
            rpcAddress: 127.0.0.1:7233
dcRedirectionPolicy:
    policy: ""
services:
    frontend:
        rpc:
            grpcPort: 7233
            membershipPort: 6933
            bindOnLocalHost: false
            bindOnIP: 0.0.0.0
    history:
        rpc:
            grpcPort: 7234
            membershipPort: 6934
            bindOnLocalHost: false
            bindOnIP: 0.0.0.0
    matching:
        rpc:
            grpcPort: 7235
            membershipPort: 6935
            bindOnLocalHost: false
            bindOnIP: 0.0.0.0
    worker:
        rpc:
            grpcPort: 7239
            membershipPort: 6939
            bindOnLocalHost: false
            bindOnIP: 0.0.0.0
archival:
    history:
        state: enabled
        enableRead: true
        provider:
            filestore: null
            gstorage: null
            s3store:
                region: us-east-2
                endpoint: null
                s3ForcePathStyle: false
    visibility:
        state: enabled
        enableRead: true
        provider:
            filestore: null
            s3store:
                region: us-east-2
                endpoint: null
                s3ForcePathStyle: false
            gstorage: null
publicClient:
    hostPort: ""
    forceTLSConfig: ""
dynamicConfigClient:
    filepath: /etc/temporal/config/dynamic_config.yaml
    pollInterval: 10s
namespaceDefaults:
    archival:
        history:
            state: enabled
            URI: s3://bucket
        visibility:
            state: enabled
            URI: s3://bucket
otel: {}
```
