### ISSUE TITLE
`web` is unable to create `./config/docker.yaml`

### ISSUE THREAD

**Issue by marklonquist** [temporalio/temporal#5104]
## Expected Behavior
`web` can create `./config/docker.yaml`

## Actual Behavior
error:
`2023/11/10 13:30:45 unable to create open ./config/docker.yaml: permission denied`

## Steps to Reproduce the Problem

  1. deploy with security contexts:
```yaml
containerSecurityContext:
    runAsNonRoot: true
    allowPrivilegeEscalation: false
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
```
  2. observe that `web` will fail to start

## Specifications

  - Version:
      ```yaml
      image:
        repository: temporalio/ui
        tag: 2.21.3



     helm chart info:
       version: 0.29.0
       appVersion: 1.22.1
      ```
  - Platform: `GKE Kubernetes`
