### ISSUE TITLE
Cassandra Consistency and SerialConsistency should be configurable

### ISSUE THREAD

**Issue by rfwagner** [temporalio/temporal#512]
There are 10 or so places throughout the Temporal code base where a gocql.ClusterConfig struct is created in order to create a new Cassandra session. In each location, the Consistency and SerialConsistency levels are hardcoded, e.g.:

```
	cluster.Consistency = gocql.LocalQuorum
	cluster.SerialConsistency = gocql.LocalSerial

```

These consistency levels should both be configurable. They should be made part of the Config.Cassandra struct which holds existing configurable Cassandra settings like username, password, keyspace name etc.

Ultimately these should be settable in the yaml config with something like:

```

    persistence:
      defaultStore: cass-default
      visibilityStore: cass-visibility
      numHistoryShards: 4
      datastores:
        cass-default:
          cassandra:
            keyspace: mykeyspace
            user: myuser
            consistency: Quorum
            serialConsistency: Serial
            ...

```
