### ISSUE TITLE
Key Rotation for Temporal Authentication and Authorization using Azure AD

### ISSUE THREAD

**Issue by giuliohome** [temporalio/temporal#5127]
## Expected Behavior

We would expect a way to make Temporal aware of the key rotation.

## Actual Behavior

It looks like Temporal caches the RSA keys returned from "keySourceURIs". See https://stackoverflow.com/questions/77305403/need-with-with-authentication-in-temporal-cluster

## Steps to Reproduce the Problem

Steps described for example here https://devblogs.microsoft.com/ise/2023/07/12/temporal-mtls-sso/#3-running-temporal-server-with-authorization-enabled

## Specifications

  - Version: Latest Temporal.io
  - Platform: Kubernetes installation via Helm Chart

**Comment by giuliohome** [comment]
Actually the [callback](https://github.com/temporalio/temporal/blob/a93926c8df968e784caadc030e7bdb9f2635ffde/common/authorization/default_token_key_provider.go#L119-L133) should periodically refresh the key

```golang
func (a *defaultTokenKeyProvider) timerCallback() {
	for {
		select {
		case <-a.stop:
			return
		case <-a.ticker.C:
		}
		if a.config.HasSourceURIsConfigured() {
			err := a.updateKeys()
			if err != nil {
				a.logger.Error("error while refreshing token keys: ", tag.Error(err))
			}
		}
	}
}
```

Will close this soon if it is confirmed to work.

**Comment by giuliohome** [comment]
Tested with personal azure subscription and demo cluster DOKR.
The configuration is done via environment variables:

```yaml
web:
    additionalEnv:
      - name: "TEMPORAL_AUTH_ENABLED"
        value: "true"
      - name: "TEMPORAL_AUTH_PROVIDER_URL"
        value: "https://login.microsoftonline.com/.../v2.0"
      - name: "TEMPORAL_AUTH_ISSUER_URL"
        value: "https://login.microsoftonline.com/.../v2.0"
      - name: "TEMPORAL_AUTH_CALLBACK_URL"
        value: "https://mytemporal.giuliohome.com/auth/sso/callback"
      - name: "TEMPORAL_AUTH_SCOPES"
        value: "openid,api://.../default"
      - name: "TEMPORAL_AUTH_CLIENT_ID"
        value: "..."
      - name: "TEMPORAL_AUTH_CLIENT_SECRET"
        value: "..."
    config:
      auth:
        enabled: true
        authorization:
          authorizer: default
          claimMapper: default
          permissionsClaimName: roles
          jwtKeyProvider:
            keySourceURIs:
              - https://login.microsoftonline.com/.../discovery/discovery/v2.0/keys
            refreshInterval: "5m"
```


in my case I used cloudflare dns to get automatic tls and I have to add an annotation for my nginx ingress

```yaml
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-buffer-size: 10k
```
The key rotation process seems to be (semi)manual afaics. I've had to add a new secret in the client secrets tab of azure app registration and then I've had to `helm upgrade -f` the new value of

```yaml
web:
    additionalEnv:

      - name: "TEMPORAL_AUTH_CLIENT_SECRET"
        value: "..."
```

![immagine](https://github.com/temporalio/temporal/assets/3272563/6c7a2c79-6b33-409a-a7ac-828fd39e8c0b)
