### ISSUE TITLE
SecondaryVisbilityStore validation failed

### ISSUE THREAD

**Issue by vanhtuan0409** [temporalio/temporal#5489]
## Expected Behavior

I want to migrate the visibility store from ES to Postgres using Dual Visibility Store feature. Expected behavior to be able to dual write to both ES and Postgres. Temporal config:

```
  visibilityStore: es-visibility
  secondaryVisibilityStore: pg-visibility
  datastores:
    pg-visibility:
      SQL:
    es-visibility:
      elasticsearch:
```

## Actual Behavior

Upon starting the server, I got the following error `persistence config: cannot set secondaryVisibilityStore when visibilityStore is setting elasticsearch datastore`

## Steps to Reproduce the Problem

  1. Setup the config as above
  2. Start temporal server

## Specifications

  - Version: 1.22.3
  - Platform: Linux
