### ISSUE TITLE
creating a dev environment using podman instead of docker-compose

### ISSUE THREAD

**Issue by Lercher** [temporalio/temporal#550]
This is more an offer instead of a request: My corporation only allows containers running in user space, so docker is a no-go for me. I wanted to run a dev environment using podman instead of docker-compose. Here is a yaml file I'd like to share with the community for version 0.26 plus cassandra: https://gitlab.com/lercher/wf/-/blob/master/temporal.yaml

After downloading, a local pod can be created and started via `podman play kube temporal.yaml`. Starting, stoping and removing the pod: `podman pod start/stop/rm temporal`. Hoping that helps ppl like me with this kind of "root" problems.

My suggestion is that something like that finds its way into the code base and the documentation, eventually. As I'm quite un-experienced using containers, that's probably a better option compared to what I did.

<hr>

For easier reference, this is the current content of the file mentioned:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: temporal
spec:
  restartPolicy: Always

  containers:

  - name: cassandra
    image: cassandra:3.11
    ports:
    - containerPort: 9042
      hostPort: 9042
    resources: {}
  
  - name: temporal-srv
    image: temporalio/auto-setup:0.26.0
    env:
    - name: CASSANDRA_SEEDS
      value: localhost
    - name: DYNAMIC_CONFIG_FILE_PATH
      value: config/dynamicconfig/development.yaml
    - name: BIND_ON_IP
      value: 127.0.0.1
    ports:
    - containerPort: 7233
      hostPort: 7233
    resources: {}

  - name: temporal-web
    image: temporalio/web:0.26.0
    env:
    - name: TEMPORAL_GRPC_ENDPOINT
      value: localhost:7233
    ports:
    - containerPort: 8088
      hostPort: 8088
    resources: {}
```
