### ISSUE TITLE
Archival does not show list of archived workflows

### ISSUE THREAD

**Issue by jmichaelsmotus** [temporalio/temporal#5624]
## Expected Behavior
Viewing the Archival tab for a namespace which has archived workflows should display them.

## Actual Behavior
The Archival tab is displaying the message "No Workflows running in this Namespace" even though there are archived workflows present in the configured archival S3 bucket. The GET call to `api/v1/namespaces/<namespace>/archived-workflows?query=` is failing with an HTTP 400.

## Steps to Reproduce the Problem

  1. Create an S3 bucket for Archival.
  2. Ensure that Temporal's K8s service account has the below IAM permissions, changing the bucket name here to match.
```
{
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketLocation",
                "s3:PutObject",
                "s3:PutObjectAcl",
                "s3:GetObject",
                "s3:GetObjectAcl",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::temporal-workflow-archive-bucket",
                "arn:aws:s3:::temporal-workflow-archive-bucket/*"
            ]
        }
    ]
}
```
  4. Add the below configuration to the Temporal Helm chart, changing the bucket name here to match.
```
config:
    archival:
      history:
        state: enabled
        enableRead: true
        provider:
          s3store:
            region: <aws region>
      visibility:
        state: enabled
        enableRead: true
        provider: 
          s3store:
            region: <aws region>

    namespaceDefaults:
      archival:
        history:
          state: enabled
          URI: s3://temporal-workflow-archive-bucket
        visibility:
          state: enabled
          URI: s3://temporal-workflow-archive-bucket
```
  5. Turn on archival and visibility for a namespace that has workflows running, and wait for the retention period.
  6. View the archival bucket and observe that there are files present for those archived workflows.
  7. Go to the Archival tab for that namespace and observe the message "No Workflows running in this Namespace" and the failed call to `api/v1/namespaces/<namespace>/archived-workflows?query=`.

## Specifications

  - Version: 1.22.5
  - Platform: AWS, EKS, amd64

**Comment by jmichaelsmotus** [comment]
Some more information about this issue:

The call to `api/v1/namespaces/banking/archived-workflows?query=` which returns an HTTP 400 is giving the following error:
```json
{
  "code": 3,
  "message": "Cluster is not configured for reading archived visibility records."
}
```

This error message is defined here:
```golang
errClusterIsNotConfiguredForReadingArchivalVisibility = serviceerror.NewInvalidArgument("Cluster is not configured for reading archived visibility records.")
```
https://github.com/temporalio/temporal/blob/main/service/frontend/errors.go#L62

And seems to be only used here:
```golang
if !wh.archivalMetadata.GetVisibilityConfig().ReadEnabled() {
    return nil, errClusterIsNotConfiguredForReadingArchivalVisibility
}
```
https://github.com/temporalio/temporal/blob/main/service/frontend/workflow_handler.go#L2131

It looks like ultimately the value of `wh.archivalMetadata.GetVisibilityConfig().ReadEnabled()` comes from the configuration loaded from the config yaml, since `cfg.Archival.Visibility.EnableRead` maps to the yaml key path `config.visibility.enableRead`:
```golang
func ArchivalMetadataProvider(dc *dynamicconfig.Collection, cfg *config.Config) archiver.ArchivalMetadata {
	return archiver.NewArchivalMetadata(
		dc,
		cfg.Archival.History.State,
		cfg.Archival.History.EnableRead,
		cfg.Archival.Visibility.State,
		cfg.Archival.Visibility.EnableRead,
		&cfg.NamespaceDefaults.Archival,
	)
}
```
https://github.com/temporalio/temporal/blob/main/common/resource/fx.go#L350

However, I can see from the temporal-frontend Pod's logs that it's loading config/docker.yaml:
```
2024/03/29 15:52:04 Loading config; env=docker,zone=,configDir=config
2024/03/29 15:52:04 Loading config files=[config/docker.yaml]
```

And if I shell into the container, I can see the config file does have the correct configuration:
```
temporal-frontend-f56454dff-7dr26:/etc/temporal$ cat config/docker.yaml
<...>
archival:
  history:
    state: "enabled"
    enableRead: true
    provider:
      s3store:
        logLevel: 0
        region: #######
  visibility:
    state: "enabled"
    enabledRead: true
    provider:
      s3store:
        logLevel: 0
        region: #######

namespaceDefaults:
  archival:
    history:
      URI: #######
      state: enabled
    visibility:
      URI: #######
      state: enabled
<...>
```

So why is temporal-frontend acting like this is not configured?

**Comment by gad26032** [comment]
Same issue. But i use local file system as a backend.
```
  archival:
    history:
      state: "enabled"
      enableRead: true
      provider:
        filestore:
          fileMode: "0666"
          dirMode: "0766"
    visibility:
      state: "enabled"
      enableRead: true
      provider:
        filestore:
          fileMode: "0666"
          dirMode: "0766"

  namespaceDefaults:
    archival:
      history:
        state: "enabled"
        URI: "file:///home/temporal/temporal_archival/data"
      visibility:
        state: "enabled"
        URI: "file:///home/temporal/temporal_vis_archival/data"
```
describe namespace
```
temporal-admintools-94844b8c5-v5957:/etc/temporal$ temporal operator namespace describe dev
  NamespaceInfo.Name                    dev                                               
  NamespaceInfo.Id                      c975b631-f109-41f7-865a-04b341fbe922              
  NamespaceInfo.Description                                                               
  NamespaceInfo.OwnerEmail                                                                
  NamespaceInfo.State                   Registered                                        
  NamespaceInfo.Data                    map[]                                             
  Config.WorkflowExecutionRetentionTtl  24h0m0s                                           
  ReplicationConfig.ActiveClusterName   active                                            
  ReplicationConfig.Clusters            [&ClusterReplicationConfig{ClusterName:active,}]  
  Config.HistoryArchivalState           Enabled                                           
  Config.VisibilityArchivalState        Enabled                                           
  IsGlobalNamespace                     false                                             
  FailoverVersion                                                                      0  
  FailoverHistory                       []                                                

```

on temporal-history pod

```
temporal-history-6c4ffd4497-gdjzn:~$ tree 
.
├── temporal_archival
│   └── data
│       ├── 9432711404182916402104093526875229053638092447613532531101_0.history
│       ├── 94327114041829164021084163317621728861618148438391857267770_0.history
│       ├── 94327114041829164021091822365132548957316345918779004043580_0.history
│       ├── 9432711404182916402115342497942727559928603905498755678542_0.history
│       ├── 94327114041829164021187177523304437776814507355958716097471_0.history
│       ├── 9432711404182916402121795187567593117734563104817072754649_0.history
│       ├── 94327114041829164021369425147835939224213576829868932098155_0.history
│       ├── 9432711404182916402142070436314182125369381270941919231101_0.history
│       ├── 94327114041829164021471306864951670870711793389869607115790_0.history
│       ├── 94327114041829164021506708775943436350214211353399726364414_0.history
│       ├── 9432711404182916402153278125069079137315839587885622791956_0.history
│       ├── 9432711404182916402156890200560994755374282318068498157807_0.history
│       ├── 943271140418291640217516097016582626084281047780464377597_0.history
│       ├── 94327114041829164021837105007265925318612098165724614274354_0.history
│       ├── 9432711404182916402254573994492637874517488082703656383857_0.history
│       ├── 9432711404182916402317943577272964098815450311660785219675_0.history
│       ├── 943271140418291640233758127846927679835193949429972358239_0.history
│       ├── 943271140418291640235115611219124307513107041130708393426_0.history
│       ├── 943271140418291640237926995589368900226084062552604701383_0.history
│       ├── 943271140418291640239807637617228025826704028452595363645_0.history
│       ├── 943271140418291640241261817242969513985221394463637855399_0.history
│       ├── 9432711404182916402422184944781623571410055352159055992148_0.history
│       ├── 9432711404182916402669434261262196544715426148248108271996_0.history
│       ├── 943271140418291640267761469647471156073957396600076799429_0.history
│       ├── 9432711404182916402681724211559379228415105004922719971755_0.history
│       ├── 943271140418291640274535540260410957175475395827575704226_0.history
│       ├── 943271140418291640279385873525816977019003041482303634508_0.history
│       ├── 9432711404182916402798382296605276838416607145351649060818_0.history
│       ├── 9432711404182916402939192926206646876815312822523284306755_0.history
│       ├── 943271140418291640294944933450628752312303702040985760010_0.history
│       ├── 943271140418291640295710937541081983910480885637690598829_0.history
│       └── 9432711404182916402970473396858808043215067898247463723775_0.history
└── temporal_vis_archival
    └── data
        └── c975b631-f109-41f7-865a-04b341fbe922
            ├── 1714523543567043851_3107041130708393426.visibility
            ├── 1714523665551876245_8603905498755678542.visibility
            ├── 1714523666297386886_281047780464377597.visibility
            ├── 1714523666687464991_15067898247463723775.visibility
            ├── 1714523690726450192_10480885637690598829.visibility
            ├── 1714523724303522465_5475395827575704226.visibility
            ├── 1714523811355670191_10055352159055992148.visibility
            ├── 1714523812305221480_12098165724614274354.visibility
            ├── 1714523880581925225_6704028452595363645.visibility
            ├── 1714523937782704036_3957396600076799429.visibility
            ├── 1714523940832462245_11793389869607115790.visibility
            ├── 1714523958672627173_15839587885622791956.visibility
            ├── 1714523961296364414_15450311660785219675.visibility
            ├── 1714524060679383606_2303702040985760010.visibility
            ├── 1714524087952532544_14507355958716097471.visibility
            ├── 1714524088077145000_18148438391857267770.visibility
            ├── 1714524088311171432_13576829868932098155.visibility
            ├── 1714524315062587283_9003041482303634508.visibility
            ├── 1714524319106105659_16345918779004043580.visibility
            ├── 1714524319204245324_15105004922719971755.visibility
            ├── 1714524348336002586_5193949429972358239.visibility
            ├── 1714524392055365528_16607145351649060818.visibility
            ├── 1714524441551730509_15426148248108271996.visibility
            ├── 1714524470642662186_4282318068498157807.visibility
            ├── 1714524494935150924_6084062552604701383.visibility
            ├── 1714524497579551390_14211353399726364414.visibility
            ├── 1714524517781901022_8092447613532531101.visibility
            ├── 1714524587528616633_9381270941919231101.visibility
            ├── 1714526336198869418_5221394463637855399.visibility
            ├── 1714527023940092587_4563104817072754649.visibility
            ├── 1714527023998615275_17488082703656383857.visibility
            └── 1714527261355949256_15312822523284306755.visibility

5 directories, 64 files
```
But when i try to get history, i get this

```
temporal-admintools-94844b8c5-v5957:/etc/temporal$ temporal workflow list --archived dev
Error: unable to list archived workflow executions: Namespace is not configured for visibility archival.
('export TEMPORAL_CLI_SHOW_STACKS=1' to see stack traces)
```

Web UI just doesn't show anything on the Archived page
