### ISSUE TITLE
Enable wildcard namespace definition when setting namespace RPS

### ISSUE THREAD

**Issue by kelkawi-a** [temporalio/temporal#6237]
**Is your feature request related to a problem? Please describe.**
It seems there is a way of setting namespace RPS limits as [outlined here](https://community.temporal.io/t/rate-limiting-by-namespace/1335/7). To enable a more dynamic approach, it would be useful to be able to define wildcard rules that get applied to namespaces (e.g. `stg-*` means any namespaces matching this rule such as `stg-test` will have this rule applied to it).

**Describe the solution you'd like**
Current functionality:
```yaml
frontend.namespacerps:
- value: 2000
- value: 100
  constraints:
    namespace: "namespaceA"
- value: 500
  constraints:
    namespace: "namespaceB"
```

Requested functionality:
```yaml
frontend.namespacerps:
- value: 1000
- value: 500
  constraints:
    namespace: "stg-*"
- value: 600
  constraints:
    namespace: "prod-*"
```

**Describe alternatives you've considered**
The alternative here is updating the server config every time a new namespace is added to which we want to apply RPS limits. The proposed approach can allow a more generic configuration of RPS limits to namespaces.

**Additional context**
N/A
