### ISSUE TITLE
Expand configuration for Elastic to support serverless

### ISSUE THREAD

**Issue by thegedge** [temporalio/temporal#6253]
**Is your feature request related to a problem? Please describe.**

We were looking to use Elastic's serverless option for our visibility store, but to connect we would need to set an [`Authorization`](https://www.elastic.co/docs/current/serverless/elasticsearch/get-started#test-connection) header, which currently doesn't appear to be supported by the config for the ES client: https://github.com/temporalio/temporal/blob/66ab754e7e8d60421678457df1914fa7ddae9dc3/common/persistence/visibility/store/elasticsearch/client/config.go#L45-L60

**Describe the solution you'd like**

I'd like to be able to add a configuration like the following:

```yaml
elasticsearch:
  # ...
  headers:
    Authorization: "ApiKey {{ .Env.TEMPORAL_ES_VISIBIILITY_STORE_PASSWORD }}"
```

**Describe alternatives you've considered**

Another option would be to have this kind of a format:

```yaml
elasticsearch:
  # ...

  auth:
    basic:
      username: "..."
      password: "..."
    # or
    elastic:
      apiKey: "..."
```

But it feels far less flexible and a bit more complicated to implement.
 
Other than that, I can't really think of any alternative, besides having to set up a proxy that adds the header. Ideally, we avoid the operational overhead of another proxy and just do it straight on the client.
