### ISSUE TITLE
Unable to add search attribute when using gstorage archiver with application-default service account

### ISSUE THREAD

**Issue by HoangViet144** [temporalio/temporal#7981]
## Expected Behavior
Able to add search attribute for mysql visibility store

## Actual Behavior
Received error `"Failed to add search attributes to store mysql8: Unable to save search attributes: something went wrong, please retry (6b50ceaa)."`. In internal-frontend deployment log, I found this error `"error":"unable to find bootstrap container for the given service name"`

After searching around the source code, the given error is from https://github.com/temporalio/temporal/blob/main/common/archiver/provider/provider.go#L86. I suppose it is due to I setup GCS using GCP application default service account:
```
  archival:
    history:
      state: "enabled"
      enableRead: true
      provider:
        gstorage:
          credentialsPath: ""
    visibility:
      state: "enabled"
      enableRead: true
      provider:
        gstorage:
          credentialsPath: ""
```

However, this line (https://github.com/temporalio/temporal/blob/main/common/archiver/gcloud/connector/client.go#L60) said that it is still OK to use application default service account. I can even use archival feature with this setup. But when I add search feature, it returns error

## Steps to Reproduce the Problem

  1. Setup temporal using helm
  2. Enable archival feature with provider is GCS and using application default service account
  3. Create search feature for a particular namespace

## Specifications

  - Version: 1.27.2
  - Platform: GKE
