### ISSUE TITLE
Failed DB migration (PostgreSQL): auto-setup:1.0.0 -> auto-setup:1.1.0

### ISSUE THREAD

**Issue by kop** [temporalio/temporal#862]
## Expected Behavior

Migration script runs correctly.

## Actual Behavior

```
temporal_1              | + temporal-sql-tool --plugin postgres --ep postgres -u root -p 26257 --db temporal_visibility update-schema -d /etc/temporal/schema/postgres/visibility/versioned
temporal_1              | 2020/10/15 18:13:54 UpdateSchemeTask started, config=&{DBName: TargetVersion: SchemaDir:/etc/temporal/schema/postgres/visibility/versioned IsDryRun:false}
temporal_1              | 2020/10/15 18:13:54 error listing schema dir:open /etc/temporal/schema/postgres/visibility/versioned: no such file or directory
temporal_1              | Unable to start server: sql schema version compatibility check failed: version mismatch for keyspace/database: "temporal". Expected version: 1.1 cannot be greater than Actual version: 1.0.
```

## Steps to Reproduce the Problem

  1. Start temporalio/auto-setup:1.0.0.
  2. Stop it.
  3. temporalio/auto-setup:1.1.0.

```
  temporal:
    image: temporalio/auto-setup:1.1.0
    ports:
      - "7233:7233"
    environment:
      DB: postgres
      DB_PORT: 26257
      POSTGRES_USER: root
      POSTGRES_SEEDS: postgres
      DYNAMIC_CONFIG_FILE_PATH: config/dynamicconfig/development.yaml
    depends_on:
      - cockroachdb
    links:
      - cockroachdb:postgres
```

## Specifications

  - Version: 1.0.0, 1.1.0.
